### ISSUE TITLE
Epic: Use az capi to create kubernetes clusters for testing

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/azure-capi-cli-extension#46]
TODOs:

- [x] #85
- [x] #98
- [x] #49
- [x] default to Azure management cluster vs. local management cluster
- [ ] CNI / addons via ClusterResourceSet (+ turn on feature flag by default)
- [x] provide a convenience for configuring the node OS (either allow passing in script to run on worker/control plane nodes or some easy way to apply a Daemonset on the workload cluster) #97
- [ ] de-duplicate template composition, improve composition of templates (individual CRDs) in CAPZ so we can rely on those fully

**Comment by CecileRobertMichon** [comment]
> CNI / addons via ClusterResourceSet (+ turn on feature flag by default)

@mboersma looks like this is already done?

**Comment by mboersma** [comment]
We do install CNI from the Calico addons template in the CAPZ repo, but it doesn't involve ClusterResourceSet, just `kubectl apply` of that manifest. So I was assuming there is more work to do here...

**Comment by CecileRobertMichon** [comment]
Got it, it does seem like we are setting the feature flag though: https://github.com/Azure/azure-capi-cli-extension/blob/main/src/capi/azext_capi/custom.py#L109

**Comment by mboersma** [comment]
I'm going to close this epic as @DannyBrito has implemented basically everything here.
